project:
  type: website

website:
  title: "Computational Analysis of Multilingual Book Reviews"
  site-url: ""
  repo-url: https://github.com/IGELsociety/CHR2024-book-reviews-workshop
  open-graph: true
  twitter-card:
    creator: ""
    card-style: summary_large_image
    image: ""
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Tutorial
        menu:
          - href: packages-and-data.html
            text: "0: Packages and Data"
      - href: slides.html
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
